[project]
name = "stocks-monorepo"
version = "0.1.0"
requires-python = ">=3.11,<3.14"

[tool.uv.workspace]
members = [
  "apps/*",
  "packages/*"
]

[tool.ruff]
src = [
 "apps/stocks/src",
 "apps/lstm/src"
]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I"]
