[project]
name = "commonlib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Stevan H. Moeladi", email = "stevan.moeladi@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "tensorflow>=2.20.0",
    "yfinance>=0.2.66",
]

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
